name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build APK
        run: gradle assembleDebug --stacktrace --no-daemon

      - name: Find APK
        run: find app/build/outputs/apk -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FooladAfza-Android-APK
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
